### PR TITLE
[Doc.] - Added notes on using low level samples

### PR DESCRIPTION
**Pull request by Andre-Nascimento-MSFT**
# Checklist
- [x] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-c/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- If this is a modification that impacts the behavior of a public API
  - [ ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.
- I submitted this PR against the correct branch: 
  - [X] This pull-request is submitted against the `master` branch. 
  - [ ] I have merged the latest `master` branch prior to submission and re-merged as needed after I took any feedback.
  - [ ] I have squashed my changes into one with a clear description of the change.

# Reference/Link to the issue solved with this PR (if any)
https://github.com/Azure/azure-iot-sdk-c/issues/636

# Description of the problem

# Description of the solution

### CODE REVIEW

**Comment by Andre-Nascimento-MSFT** [comment]
Hi @ewertons, thanks for the review, changes submitted

**Comment by Andre-Nascimento-MSFT** [comment]
Hi @ewertons, any updates on the gate availability?

**Comment by YoDaMa** [comment]
@Andre-Nascimento-MSFT validating your PR now

**Comment by Andre-Nascimento-MSFT** [comment]
Thanks! 👍

**Pull request merged**
