### PR TITLE
Fix issue #647

### PR DESCRIPTION
**Pull request by ArthurMa1978**
# Checklist
- [x] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-c/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- If this is a modification that impacts the behavior of a public API
  - [ ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.
- I submitted this PR against the correct branch: 
  - [x] This pull-request is submitted against the `master` branch. 
  - [x] I have merged the latest `master` branch prior to submission and re-merged as needed after I took any feedback.
  - [x] I have squashed my changes into one with a clear description of the change.

# Reference/Link to the issue solved with this PR (if any)
[#647 Failed to connect to iothub when use DPS individual enrollment](https://github.com/Azure/azure-iot-sdk-c/issues/647)

# Description of the problem
When using the DPS individual enrollment to connect IoT DevKit with IoTHub, passed the provision and assigning stage but failed when connect to IoTHub.

# Description of the solution
This issue came from a code change of **GetTransportProviderIfNecessary** in the *iothub_client\src\iothubtransport_mqtt_common.c* file:
>Previously, it could process both 
>`transport_data->saved_tls_options` 
>and 
>`IoTHubClient_Auth_Set_xio_Certificate`, 
>but one code change add a `else` before 
>`if (IoTHubClient_Auth_Get_Credential_Type(transport_data->authorization_module) == IOTHUB_CREDENTIAL_TYPE_X509_ECC)` 
>which caused the `IoTHubClient_Auth_Set_xio_Certificate` be skipped if `transport_data->saved_tls_options` is not NULL. 
>This change could fix the issue of still process the X509 cert even after `OptionHandler_FeedOptions` failed, but ran into the `if ... else ...` trap.

To fix and avoid deep indentation, my change is just `return __FAILURE__` once get error.

### CODE REVIEW

**Comment by massand** [comment]
@ArthurMa1978 please add relevant tests to iothub transport UTs for this fix, as per our guidelines.

**Comment by jebrando** [comment]
@ArthurMa1978 I'm having issue understanding what the issue this is attempting to fix.  We can talk about this offline.

**Comment by massand** [comment]
@ArthurMa1978 We have had some general fixes for MBED targets as well as mqtt transport fixes related to X509 and SAS tokens such as #846

**Pull request closed without merging**
