### PR TITLE
Update feature matrix

### PR DESCRIPTION
**Pull request by yzhong94**
Updated service feature matrix and added reference to C set options doc.

### CODE REVIEW

**Comment by kiranpradeep** [comment]
@ewertons The below are related to feature matrix
1. Retry policies section -> This matrix shows retry policy being limited to AMQP/AMQP_WS. Is that correct?
2. Upload to blob section -> "but can be initiated from a client using any protocol for other operations." How can a blob upload be initiated by MQTT or AMQP protocol? Any clarity is helpful.

**Comment by yzhong94** [comment]
@ewertons I added the latest change.  Please review and merge.

**Comment by ewertons** [comment]
The changes are good. Thanks.

**Comment by tameraw** [comment]
@kiran pradeep
1. Retry policy exists on AMQP, AMQP_WS, MQTT, MQTT_WS. Hence we're updating the matrix to reflect that.
2. HTTP is the protocol used to upload to Azure Storage no matter which protocol you chose initially to communicate with IoT Hub service.

---
In reply to: [339533906](https://github.com/Azure/azure-iot-sdk-c/pull/272#issuecomment-339533906) [](ancestors = 339533906)

**Comment by kiranpradeep** [comment]
@tameraw The retry policy is still not marked for HTTP. Does this mean HTTP protocol data is never reattempted? I felt iothub_client_sample_http.c([1](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_http/iothub_client_sample_http.c)) retried.

**Pull request merged**
