### PR TITLE
Osxsupport

### PR DESCRIPTION
**Pull request by cwrenniks**
With these changes I'm able to build the C SDK on OSX. Also, I added a `-g "Xcode"` option for the build.sh script to enable Xcode project creation.

### CODE REVIEW

**Comment by cwrenniks** [comment]
Thanks @markrad. I just added the -n flag to sysctl which should solve that problem. @damonbarry, no haven't yet.

**Comment by cwrenniks** [comment]
@damonbarry, created pull requests on c-utility, uamqp, and umqtt. Should be good to go. Let me know if there is anything else required.

**Comment by anporumb** [comment]
This has been merged manually into the mainline (master), we now have osx/appleclang support.

Best Regards,
Andrei Porumb

**Comment by damonbarry** [comment]
Well, the one thing in this PR that didn't correspond to anything in our repo is the setup script (setup.sh). Because we aren't providing a build script for OSX (we're moving toward documenting the CMake steps, rather than wrapping CMake in our own build scripts, with their attendant bugs and oddities), there isn't a logical place to store a setup script. But I just checked in a major overhaul of our [setup doc](https://github.com/Azure/azure-iot-sdk-c/blob/b0b31e03b2447c82467045997853b46cc2dfc184/doc/devbox_setup.md) (commit b0b31e0), which covers all the steps that were in the setup script, and documents the CMake steps for building on Mac, Linux, and Windows.

**Pull request closed without merging**
