### PR TITLE
Add platform_init() to iothubserviceclient samples

### PR DESCRIPTION
**Pull request by abhatikar**
Fix curl_easy_perform() failed: Out of memory error seen when executing iothub_devicemethod and iothub_devicetwin iothub_service_client samples

### CODE REVIEW

**Comment by anporumb** [comment]
Hello @abhatikar 

Thank you for your contribution, can you please sign off the CLA so we can take it?

Best Regards,
Andrei Porumb

**Comment by abhatikar** [comment]
@anporumb I have signed the CLA.
Could you please tell me the next steps ?

Best regards
Abhijeet

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by anporumb** [comment]
This issue has already been fixed in master.

Thank you.

Best Regards,
Andrei Porumb

**Pull request closed without merging**
