### PR TITLE
fixed broken link to porting guide in iothub_client readme

### PR DESCRIPTION
**Pull request by JimacoMS3**
# Checklist
- [x] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-c/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- If this is a modification that impacts the behavior of a public API
  - [ ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.
- I submitted this PR against the correct branch: 
  - [x] This pull-request is submitted against the `master` branch. 
  - [x] I have merged the latest `master` branch prior to submission and re-merged as needed after I took any feedback.
  - [x] I have squashed my changes into one with a clear description of the change.

# Reference/Link to the issue solved with this PR (if any)
None

# Description of the problem

Broken link  to the porting guide in the iothub_client/readme.md file

# Description of the solution
 
Modified the link to point to the correct spot. (Same as the link inside the sdk readme.md file)

### CODE REVIEW

**Comment by JimacoMS3** [comment]
@rafilho Greg Manyuk asked me to add you as a reviewer. I'm a content guy with IoT Hub.

**Comment by JimacoMS3** [comment]
@rafilho This PR seems to be held up on some checks. I'm utterly unfamiliar with the process here. Who can i reach out to about this? I tried closing and then re-opening the PR once before. Same result

**Comment by rafilho** [comment]
Let me see if I can start the build pipeline for it.

**Pull request merged**
