### PR TITLE
chore: update support for IoT help and msft q&a options

### PR DESCRIPTION
**Pull request by elhorton**
# Checklist
- [ ] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-c/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- If this is a modification that impacts the behavior of a public API
  - [ ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.
- I submitted this PR against the correct branch: 
  - [ ] This pull-request is submitted against the `master` branch. 
  - [ ] I have merged the latest `master` branch prior to submission and re-merged as needed after I took any feedback.
  - [ ] I have squashed my changes into one with a clear description of the change.

# Reference/Link to the issue solved with this PR (if any)

# Description of the problem

# Description of the solution

### CODE REVIEW

**Comment by elhorton** [comment]
Hi all, these are a few simple changes to our github support workflow for a couple of reasons:

adding reference to Microsoft Q&A for technical questions, the new, preferred platform for CSS engineers, MVPs, and Microsoft cloud experts to answer questions. We're trying to direct as much traffic on general questions there as possible so they don't show up as Github issues

Adding a reference and adjusting the link to the official Azure IoT Support page so that we can track how many redirects we have (important for the Azure Customer Experience team to measure success of these workflows).

Let me know if you have any questions or concerns, thanks!

**Comment by elhorton** [comment]
hi @wduraes , could you please help merge this in? not sure why it's blocking on the mxchip gate, I've tried re-running a few times

**Comment by danewalton** [comment]
@elhorton got you

**Pull request merged**
