### PR TITLE
Fix error when building without service client

### PR DESCRIPTION
**Pull request by vjrantal**
Related to Azure/azure-iot-sdk-python#26.

### CODE REVIEW

**Comment by zolvarga** [comment]
I accepted your change and would merge it, but our build system is not able to merge between repos.
Could you please create a branch in our repo with your change? Let me know the branch name and I will merge it right away.

**Comment by vjrantal** [comment]
@zolvarga Thanks for the comment. I do not have access rights to push onto your repo so can't create branches there. If I misunderstood what was asked from me, please clarify what I should do next.

**Comment by zolvarga** [comment]
@vjrantal 

You are right, you don't have access. I go ahead and merge your change and will let you know if it is in.

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
@vjrantal 

The change merged Thanks for the contribution to our repo!

Best Regards,
Zoltan

**Pull request merged**
