### PR TITLE
provisioning_client: explicitly states function prototypes

### PR DESCRIPTION
**Pull request by fgiancane8**
When building with `-Wstrict-prototypes` flag enabled, functions with no
explicit prototype are reported (i.e. `()` instead of `(void)`).

Replacing the empty parenthesis with the correct form of declaring a
function without arguments fixes the issue.

Signed-off-by: Francesco Giancane <francesco.giancane@accenture.com>

 

# Checklist
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-c/blob/master/.github/CONTRIBUTING.md).
- [ ] ~~I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).~~
- ~~If this is a modification that impacts the behavior of a public API~~
  - [ ] ~~I edited the corresponding document in the `devdoc` folder and added or modified requirements.~~
- I submitted this PR against the correct branch: 
  - [X] This pull-request is submitted against the `master` branch. 
  - [X] I have merged the latest `master` branch prior to submission and re-merged as needed after I took any feedback.
  - [X] I have squashed my changes into one with a clear description of the change.

# Description of the problem
When building the library on systems where `-Wstrict-prototypes` flag is asserted, a warning is emitted stating that each and every function prototype in this PR is not correct.

# Description of the solution
function with missing arguments `()` are signaled via that warning flag. Replacing the empty parenthesis with a correct empty argument function signature `(void)` solved the issue.

### CODE REVIEW

**Comment by danewalton** [comment]
Hi @fgiancane8 can you please update the necessary function here: https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/tests/common_prov_e2e/prov_hsm/provisioning_hsm.c

**Comment by fgiancane8** [comment]
hello @danewalton ,

Sure! Sorry I missed it. Will do as soon as possible. 

Thanks

**Comment by fgiancane8** [comment]
@danewalton ,

I took the opportunity to review all the files inside the folder you mentioned for missing/implicit prototypes. Please have a look at the modifications and give me your thoughts.

If is strictly requested, I will update the PR with a git squash single commit.

Thanks,
Francesco

**Review by jspaith — APPROVED** [review]

**Comment by ericwol-msft** [comment]
Thanks @fgiancane8 
I added a work item to add the "-Wstrict-prototypes” to the gcc builds

**Comment by fgiancane8** [comment]
@ericwol-msft ,

Thank you! You are welcome :) If by chance any other warning is raised please let me know I will gladly fix back the issue again.

Thanks everyone for your support.

Francesco

**Pull request merged**
