### PR TITLE
Update parson to v1.3.1

### PR DESCRIPTION
**Pull request by CIPop**
Updating parson to the latest version. 
There have been numerous Parson fixes since we have last updated our dependency. For a full list see https://github.com/kgabis/parson/commits/master (we are currently at hash [8beeb5e](https://github.com/kgabis/parson/tree/8beeb5ea4da5eedff8d3221307ef04855804a920)). This PR updates to latest.

### CODE REVIEW

**Review by jspaith — APPROVED** [review]

**Review by ericwol-msft — APPROVED** [review]

**Comment by CIPop** [comment]
I'm investigating an error _only_ seen on Winx64 (Winx86 works fine):

```
   "D:\a\_work\1\s\cmake\azure_iot_sdks.sln" (default target) (1) ->
       "D:\a\_work\1\s\cmake\deps\parson\parson.vcxproj.metaproj" (default target) (123) ->
       "D:\a\_work\1\s\cmake\deps\parson\parson.vcxproj" (default target) (184) ->
       (ClCompile target) -> 
         D:\a\_work\1\s\deps\parson\parson.c(599): warning C4267: '=': conversion from 'size_t' to 'unsigned long', possible loss of data [D:\a\_work\1\s\cmake\deps\parson\parson.vcxproj]


       "D:\a\_work\1\s\cmake\azure_iot_sdks.sln" (default target) (1) ->
       "D:\a\_work\1\s\cmake\serializer\tests\datamarshaller_ut\datamarshaller_ut_exe.vcxproj.metaproj" (default target) (14) ->
       "D:\a\_work\1\s\cmake\serializer\tests\datamarshaller_ut\datamarshaller_ut_exe.vcxproj" (default target) (290) ->
         D:\a\_work\1\s\deps\parson\parson.c(599): warning C4267: '=': conversion from 'size_t' to 'unsigned long', possible loss of data [D:\a\_work\1\s\cmake\serializer\tests\datamarshaller_ut\datamarshaller_ut_exe.vcxproj]
```

**Comment by CIPop** [comment]
> 

This is an int precision/conversion bug in parson. I'll submit a PR to https://github.com/kgabis/parson then pick the latest changes here.

**Comment by CIPop** [comment]
Pending https://github.com/kgabis/parson/pull/177 and a submodule hash update.

**Comment by CIPop** [comment]
Thank you @kgabis for getting this unblocked!

**Pull request merged**
